New architecture
RonasIT/react-native-starter pull request #33
Opened 2023-04-19 03:44 UTC by ekazankova

2023-05-17 17:39 UTC, ipakhomov requested changes

2023-05-17 17:39 UTC, ipakhomov commented on tsconfig.json
>        "@shared/*": [
Could you please remove this alias?

2023-05-17 17:39 UTC, ipakhomov commented on app.config.ts
> +    //         authToken: 'your-sentry-token'
Could you please remove this? Now we store auth token in [env variable](https://docs.expo.dev/guides/using-sentry/#:~:text=token%20through%20the-,SENTRY_AUTH_TOKEN,-environment%20variable%20in) within project secrets

2023-05-17 17:40 UTC, ipakhomov commented
@ekazankova as dicussed, we can include RTKQ migration from [your branch](https://github.com/RonasIT/react-native-starter/tree/ekazankova/rtk-query). Alternatively, you can open a separate PR in case this is more manageable for you

2023-05-22 04:35 UTC, ekazankova commented
@ipakhomov RTKQ is in [this request](https://github.com/RonasIT/react-native-starter/pull/34)

2023-05-22 07:58 UTC, ipakhomov approved these changes
@ekazankova thanks!

2023-05-22 07:58 UTC, merged