Veliseev/expo router
RonasIT/react-native-starter pull request #46
Opened 2023-09-07 14:26 UTC by veliseev93

2023-09-08 07:51 UTC, ipakhomov commented
@veliseev93 thanks for the update!

Could you please apply some extra enhancements?
1. Remove the `appNavigationService` and `appNavigationEpics`
2. Turn on `"strictNullChecks": true` in `tsconfig.json` and fix typescript issues
3. Update `devDependencies` related to linting and formatting

2023-09-08 08:32 UTC, ipakhomov requested changes
See required changes above

2023-09-09 12:58 UTC, ipakhomov commented
@veliseev93 let's also migrate the project to use `expo-image` instead of [current image implementation](https://github.com/RonasIT/react-native-starter/blob/main/libs/shared/ui/ui-kit/external-image/component.tsx#L4)

2023-09-11 05:07 UTC, veliseev93 commented
@veliseev93 Done, please check

2023-09-11 06:59 UTC, ipakhomov requested changes
@veliseev93 we also have linting issues reported by `lint` script - could you please fix them?

2023-09-11 06:59 UTC, ipakhomov commented on libs/shared/ui/ui-kit/external-image/component.tsx
> +    Platform.OS === 'web' ? <Image source={{ uri }} style={style} /> : <CachedImage source={{ uri }} style={style} />;
Expo image supports web as well, so we can use it directly for both platforms

2023-09-11 06:59 UTC, ipakhomov commented on package.json
>      "react-native-expo-image-cache": "^4.1.0",
This dependency can be removed

2023-09-11 07:12 UTC, veliseev93 commented
@ipakhomov Done

2023-09-11 09:43 UTC, ipakhomov approved these changes

2023-09-11 09:43 UTC, merged